image: golang:1.26

# Helpers
include:
  - template: Jobs/SAST.gitlab-ci.yml
  - template: Jobs/Container-Scanning.gitlab-ci.yml
  - template: Jobs/Dependency-Scanning.gitlab-ci.yml
  - template: Jobs/Secret-Detection.gitlab-ci.yml

  # Don't include these templates, deprecated:
  # https://docs.gitlab.com/ci/testing/code_quality/#use-the-built-in-code-quality-cicd-template-deprecated
  #- template: Jobs/Code-Intelligence.gitlab-ci.yml
  #- template: Jobs/Code-Quality.gitlab-ci.yml

variables:
  PROJECT: controller
  CI_IMAGE_BASE: $CI_REGISTRY/$CI_PROJECT_PATH
  CI_IMAGE_STAGING: $CI_IMAGE_BASE/$PROJECT:staging
  CI_IMAGE_STAGING_RELAY: $CI_IMAGE_BASE/$PROJECT-relay:staging
  CI_IMAGE_LATEST: $CI_IMAGE_BASE/$PROJECT:latest
  CI_IMAGE_LATEST_RELAY: $CI_IMAGE_BASE/$PROJECT-relay:latest
  # TODO: do we want a prod image as well?

  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: "tcp://docker:2375"

  GITLAB_ADVANCED_SAST_ENABLED: "true"
  GIT_STRATEGY: clone
  GIT_DEPTH: "0"
  CS_IMAGE: $CI_IMAGE_GLOBAL_LATEST

stages:
  - build
  - test
  - security
  - deploy

cache:
  key:
    files:
      - go.mod
  paths:
    - $HOME/go/pkg/mod

# Build stage
setup:
  stage: build
  script:
    - go get ./...
  # the results are cached, see cache key

# Build stage - binaries
test:build:native:
  image: golang:1.26
  stage: build
  script:
    - go build -o relay ./cmd/relay/main.go
    - go build -o controller ./cmd/controller/main.go
  dependencies:
    - setup
  variables:
    CONTAINER_HOSTNAME: docker

.docker_login: &docker_login
  - docker info
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

.docker_buildx: &docker_buildx
  - docker context create fedDB-context
  - docker buildx create --name fedDBBuilder --use fedDB-context
  - docker buildx inspect --bootstrap

.test.build:docker:
  image: docker:24.0.2
  stage: build
  services:
    - name: docker:24.0.2-dind
      alias: docker
  before_script:
    - *docker_login
  script:
    - echo "Building Docker image $CI_IMAGE for $DOCKERFILE"
    - docker build -t $CI_IMAGE -f $DOCKERFILE .
    - docker save -o $TAR_FILE_NAME $CI_IMAGE
    - chmod 644 $TAR_FILE_NAME
    - echo "API image created at $TAR_FILE_NAME"
  artifacts:
    paths:
      - $TAR_FILE_NAME
    expire_in: 1 hour


test:build:docker:relay:
  extends: .test.build:docker
  variables:
    CI_IMAGE: image-relay:latest
    DOCKERFILE: Dockerfile.relay
    TAR_FILE_NAME: image-latest-relay.tar

test:build:docker:controller:
  extends: .test.build:docker
  variables:
    CI_IMAGE: image-controller:latest
    DOCKERFILE: Dockerfile.staging
    TAR_FILE_NAME: image-latest-controller.tar

test:lint:
  stage: test
  script:
    - gofmt -l .
    - test -z "$(gofmt -l .)"
  dependencies:
    - setup
    - test:build:native

test:unit_test:
  image: golang:1.26
  stage: test
  script:
    - 'mkdir -p "$(dirname ${CI_PROJECT_DIR})/tmp"'
    - 'export TMP_PATH="$(dirname ${CI_PROJECT_DIR})/tmp"'
    - go test ./...
  dependencies:
    - setup
    - test:build:native
  variables:
    CONTAINER_HOSTNAME: docker

test:code_quality:
  stage: test
  image: golangci/golangci-lint:latest
  dependencies:
    - setup
  script:
    - golangci-lint run --output.code-climate.path=gl-code-quality-report.json
  artifacts:
    reports:
      codequality: gl-code-quality-report.json
    paths:
      - gl-code-quality-report.json
    expire_in: 1 week
  allow_failure: true

test:e2e:
  stage: test
  script:
    - apt-get update -qq && apt-get install -y -qq python3-pip
    - pip3 install -r e2etests/requirements.txt --break-system-packages
    - bash e2etests/e2e_test.sh
  needs:
    - setup
    - test:build:native
    - test:unit_test
    - test:code_quality

# Secuirity stage
# ─────────────────────────────────────────────────────────────────────────────
# Override all security scanning jobs

container-scanning:relay:
  extends: container_scanning
  stage: security
  needs:
    - test:build:docker:relay
  dependencies:
    - test:build:docker:relay
  variables:
    CS_IMAGE: "archive://image-latest-relay.tar"

container-scanning:controller:
  extends: container_scanning
  stage: security
  needs:
    - test:build:docker:controller
  dependencies:
    - test:build:docker:controller
  variables:
    CS_IMAGE:  "archive://image-latest-controller.tar"

# DEACTIVATED
# Otherwise auto created, however we seperately scan controller and relay images
container_scanning:
  stage: security
  script:
    - echo "This job is deactivated, as we separately scan controller and relay images"
  rules:
    - when: never

# DEACTIVATED
# There are helper scripts in the repo so gitlab will activate this job otherwise
# however we don't need security reports of helper scripts only used in developer e2etests
gemnasium-python-dependency_scanning:
  stage: security
  script:
    - echo "This job is deactivated, as we don't need security reports of helper scripts only used in developer e2etests"
  rules:
    - when: never

gemnasium-dependency_scanning:
  stage: security

secret_detection:
  dependencies:
    - setup
  stage: security
  variables:
    GIT_DEPTH: "0"

spotbugs-sast:
  stage: security
  dependencies:
    - setup
  variables:
    COMPILE: "false"
    SECURE_LOG_LEVEL: debug

gitlab-advanced-sast:
  stage: security
  dependencies:
    - setup
  artifacts:
    paths:
      - '**/trace.ctf'
    expire_in: 1 week
    when: always
  variables:
    RUNNER_SCRIPT_TIMEOUT: 50m
  timeout: 1h

# golang has an official built in vulnerability scanner
golang-vulnerability-scanning:
  stage: security
  dependencies:
    - setup
  script:
    - go install golang.org/x/vuln/cmd/govulncheck@latest
    - govulncheck --format=sarif ./... > govulncheck.sarif
  artifacts:
    paths:
      - govulncheck.sarif
    expire_in: 1 week
  allow_failure: true

# Deployment stage
.deploy:gitlab_registry:
  image: docker:latest
  stage: deploy
  services:
    - name: docker:dind
      alias: docker
  before_script:
    - *docker_login
    - *docker_buildx
  script:
    - docker buildx build --platform linux/amd64,linux/arm64/v8 --provenance false -t $CI_IMAGE -f $DOCKERFILE --push .

deploy:gitlab:controller:staging:
  extends: .deploy:gitlab_registry
  only:
   - develop
  variables:
    CI_IMAGE: $CI_IMAGE_STAGING
    DOCKERFILE: Dockerfile.staging
  dependencies:
    - test:lint
    - test:unit_test
    - test:e2e

deploy:gitlab:relay:staging:
  extends: .deploy:gitlab_registry
  only:
   - develop
  variables:
    CI_IMAGE: $CI_IMAGE_STAGING_RELAY
    DOCKERFILE: Dockerfile.relay
  dependencies:
    - test:lint
    - test:unit_test
    - test:e2e

deploy:gitlab:controller:latest:
  extends: .deploy:gitlab_registry
  only:
   - main
   - master
  variables:
    CI_IMAGE: $CI_IMAGE_LATEST
    DOCKERFILE: Dockerfile
  dependencies:
    - test:lint
    - test:unit_test
    - test:e2e

deploy:gitlab:relay:latest:
  extends: .deploy:gitlab_registry
  only:
   - main
   - master
  variables:
    CI_IMAGE: $CI_IMAGE_LATEST_RELAY
    DOCKERFILE: Dockerfile.relay
  dependencies:
    - test:lint
    - test:unit_test
    - test:e2e

# this is disabled for now as this would overwrite the controller used in featurecloud and
# therefore break featurecloud itself.
# As the fedDB only uses the gitlab images, this is not an issue.
# deploy:main:staging:
#   image: docker
#   stage: deploy:main
#   only:
#     - develop
#   variables:
#     CONTAINER_HOSTNAME: docker
#   before_script:
#     - docker info
#     - docker login -u $FEATURECLOUD_REGISTRY_USER -p $FEATURECLOUD_REGISTRY_PASSWORD $FEATURECLOUD_REGISTRY_URL
#   script:
#     - docker build -t $FEATURECLOUD_REGISTRY_URL/controller:staging -f ./Dockerfile.staging .
#     - docker push $FEATURECLOUD_REGISTRY_URL/controller:staging

#   dependencies:
#     - deploy:gitlab:staging

# deploy:main:prod:
#   image: docker
#   stage: deploy:main
#   only:
#     - master
#     - main
#   when: manual
#   variables:
#     CONTAINER_HOSTNAME: docker
#   before_script:
#     - docker info
#     - docker login -u $FEATURECLOUD_REGISTRY_USER -p $FEATURECLOUD_REGISTRY_PASSWORD $FEATURECLOUD_REGISTRY_URL
#   script:
#     - docker build -t $FEATURECLOUD_REGISTRY_URL/controller:latest -f ./Dockerfile .
#     - docker push $FEATURECLOUD_REGISTRY_URL/controller:latest

