manager:                                                # WORKFLOW MANAGER RELATED PARAMETERS
  flrunmanagerport: 8000                                    # the port where this controller will be accessible at
  appCommV2Port: 8001                                     # the port for app communication v2
  logLevelStdOut: "debug"                                 # available levels: "debug", "info", "warn", "error", "fatal"
  logLevelFile: "debug"                                   # available levels: "debug", "info", "warn", "error", "fatal"
  learningApiWsAddress: ""                              # LocalLearningAPI websocket server address. Needs to be overriden
relay:                                                  # RELAY SERVER RELATED PARAMETERS (relay server is responsible for communication between applications)
  addressTCP: "dev.federated-learning.net:9150"        # TCP port for relay communication in format host:port, without protocol/scheme
  # Use default values for mode and tlsMode
  # developers should overwrite these values
  # in the staging test environment we'd wanna test the prod settings (default)
